# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/windows/Users/0x6d6f69/Documents/UTC/S2/AI22/projet/shotten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/windows/Users/0x6d6f69/Documents/UTC/S2/AI22/projet/shotten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/windows/Users/0x6d6f69/Documents/UTC/S2/AI22/projet/shotten/CMakeFiles /run/media/windows/Users/0x6d6f69/Documents/UTC/S2/AI22/projet/shotten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/windows/Users/0x6d6f69/Documents/UTC/S2/AI22/projet/shotten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shotten

# Build rule for target.
shotten: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shotten
.PHONY : shotten

# fast build rule for target.
shotten/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/build
.PHONY : shotten/fast

shotten/Board.o: shotten/Board.cpp.o
.PHONY : shotten/Board.o

# target to build an object file
shotten/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Board.cpp.o
.PHONY : shotten/Board.cpp.o

shotten/Board.i: shotten/Board.cpp.i
.PHONY : shotten/Board.i

# target to preprocess a source file
shotten/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Board.cpp.i
.PHONY : shotten/Board.cpp.i

shotten/Board.s: shotten/Board.cpp.s
.PHONY : shotten/Board.s

# target to generate assembly for a file
shotten/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Board.cpp.s
.PHONY : shotten/Board.cpp.s

shotten/Card.o: shotten/Card.cpp.o
.PHONY : shotten/Card.o

# target to build an object file
shotten/Card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Card.cpp.o
.PHONY : shotten/Card.cpp.o

shotten/Card.i: shotten/Card.cpp.i
.PHONY : shotten/Card.i

# target to preprocess a source file
shotten/Card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Card.cpp.i
.PHONY : shotten/Card.cpp.i

shotten/Card.s: shotten/Card.cpp.s
.PHONY : shotten/Card.s

# target to generate assembly for a file
shotten/Card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Card.cpp.s
.PHONY : shotten/Card.cpp.s

shotten/Deck.o: shotten/Deck.cpp.o
.PHONY : shotten/Deck.o

# target to build an object file
shotten/Deck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Deck.cpp.o
.PHONY : shotten/Deck.cpp.o

shotten/Deck.i: shotten/Deck.cpp.i
.PHONY : shotten/Deck.i

# target to preprocess a source file
shotten/Deck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Deck.cpp.i
.PHONY : shotten/Deck.cpp.i

shotten/Deck.s: shotten/Deck.cpp.s
.PHONY : shotten/Deck.s

# target to generate assembly for a file
shotten/Deck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Deck.cpp.s
.PHONY : shotten/Deck.cpp.s

shotten/Game.o: shotten/Game.cpp.o
.PHONY : shotten/Game.o

# target to build an object file
shotten/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Game.cpp.o
.PHONY : shotten/Game.cpp.o

shotten/Game.i: shotten/Game.cpp.i
.PHONY : shotten/Game.i

# target to preprocess a source file
shotten/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Game.cpp.i
.PHONY : shotten/Game.cpp.i

shotten/Game.s: shotten/Game.cpp.s
.PHONY : shotten/Game.s

# target to generate assembly for a file
shotten/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Game.cpp.s
.PHONY : shotten/Game.cpp.s

shotten/Landmark.o: shotten/Landmark.cpp.o
.PHONY : shotten/Landmark.o

# target to build an object file
shotten/Landmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Landmark.cpp.o
.PHONY : shotten/Landmark.cpp.o

shotten/Landmark.i: shotten/Landmark.cpp.i
.PHONY : shotten/Landmark.i

# target to preprocess a source file
shotten/Landmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Landmark.cpp.i
.PHONY : shotten/Landmark.cpp.i

shotten/Landmark.s: shotten/Landmark.cpp.s
.PHONY : shotten/Landmark.s

# target to generate assembly for a file
shotten/Landmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Landmark.cpp.s
.PHONY : shotten/Landmark.cpp.s

shotten/Player.o: shotten/Player.cpp.o
.PHONY : shotten/Player.o

# target to build an object file
shotten/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Player.cpp.o
.PHONY : shotten/Player.cpp.o

shotten/Player.i: shotten/Player.cpp.i
.PHONY : shotten/Player.i

# target to preprocess a source file
shotten/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Player.cpp.i
.PHONY : shotten/Player.cpp.i

shotten/Player.s: shotten/Player.cpp.s
.PHONY : shotten/Player.s

# target to generate assembly for a file
shotten/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/Player.cpp.s
.PHONY : shotten/Player.cpp.s

shotten/main.o: shotten/main.cpp.o
.PHONY : shotten/main.o

# target to build an object file
shotten/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/main.cpp.o
.PHONY : shotten/main.cpp.o

shotten/main.i: shotten/main.cpp.i
.PHONY : shotten/main.i

# target to preprocess a source file
shotten/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/main.cpp.i
.PHONY : shotten/main.cpp.i

shotten/main.s: shotten/main.cpp.s
.PHONY : shotten/main.s

# target to generate assembly for a file
shotten/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shotten.dir/build.make CMakeFiles/shotten.dir/shotten/main.cpp.s
.PHONY : shotten/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shotten"
	@echo "... shotten/Board.o"
	@echo "... shotten/Board.i"
	@echo "... shotten/Board.s"
	@echo "... shotten/Card.o"
	@echo "... shotten/Card.i"
	@echo "... shotten/Card.s"
	@echo "... shotten/Deck.o"
	@echo "... shotten/Deck.i"
	@echo "... shotten/Deck.s"
	@echo "... shotten/Game.o"
	@echo "... shotten/Game.i"
	@echo "... shotten/Game.s"
	@echo "... shotten/Landmark.o"
	@echo "... shotten/Landmark.i"
	@echo "... shotten/Landmark.s"
	@echo "... shotten/Player.o"
	@echo "... shotten/Player.i"
	@echo "... shotten/Player.s"
	@echo "... shotten/main.o"
	@echo "... shotten/main.i"
	@echo "... shotten/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

